server:
  port: 8090
spring:
   datasource :
          url : jdbc:mysql://localhost:3306/student_db?useSSL=false
          username : root
          password : root


   jpa:
     show-sql : true
     properties :
          hibernate :
               dialect : org.hibernate.dialect.MySQL5InnoDBDialect

     hibernate :
          ddl-auto : update
